import sqlite3
kjd=sqlite3.connect('dmgfreind.db',isolation_level=None)
kjd.execute('CREATE TABLE IF NOT EXISTS DAMURU_FREIND (FIRST_NAME TEXT,LAST_NAME TEXT, AGE INTEGER, ADRRESS TEXT)STRICT')
#LET'S ADD KJD FREIND
kjd.execute('INSERT INTO DAMURU_FREIND VALUES("Patrick", "NIYIGENA",20 ,"KAYONZA")')
kjd.execute('INSERT INTO DAMURU_FREIND VALUES("Simeon", "BYIRINGIRO", 20, "KAYONZA")')
kjd.execute('INSERT INTO DAMURU_FREIND VALUES("Ange", "NIYIGENA" ,21, "GASABO")')
kjd.execute('INSERT INTO DAMURU_FREIND VALUES( "MarieclaiRe", "MUKAMUTSI", 27 ,"CYANIKA")')
kjd.execute('INSERT INTO DAMURU_FREIND VALUES("Jacqueline","UWAMBAJEMARIYA", 23," KAGOGO")')
kjd.execute('INSERT INTO DAMURU_FREIND VALUES("Benitha", "UGANIMANA", 20, "KARONGI")')
kjd.execute('INSERT INTO DAMURU_FREIND VALUES("Bonfils", "UWAMUNGU", 22,"NYAGATARE"  )')
for row in kjd.execute('SELECT * FROM DAMURU_FREIND'):
	print(row)
#let's create table of damuru freind with age >23
kjd.execute('CREATE TABLE IF NOT EXISTS DAMURU_FREIND_age_GREATER23  as SELECT * FROM DAMURU_FREIND WHERE AGE>23')
print("dmgfreind WITH AGE GREATER THAN 23:\n")
print(kjd.execute('SELECT * FROM DAMURU_FREIND_age_GREATER23 ').fetchall())
#LET'S DROP THAT ABOVE TBLE
kjd.execute('DROP TABLE DAMURU_FREIND_age_GREATER23')
#ADD COLUMN TO DAMURU FRIEND
kjd.execute('ALTER TABLE DAMURU_FREIND ADD COLUMN PHONE TEXT DEFAULT "078....." ')
#LET'S FILL PHONE COLUMN
for row in kjd.execute('SELECT * FROM DAMURU_FREIND'):
	print(row)
